version: 2.1

jobs:
  audit_job:
    docker:
        - image: circleci/node
    steps:
      - checkout
      - run:
          name: "npm audit結果を.npm_audit.logファイルに格納する"
          command: |
            npm audit --parseable | awk -F $'\t' '{print $4}' >> .npm_audit.log || true
      - run:
          name: "GitHub Issueに投げる"
          command: |
            body=`cat /home/circleci/project/.npm_audit.log`
            echo ${body}
            curl -u "${GITHUB_USER}":"${GITHUB_TOKEN}" -X POST -i -d '{"title":"npm audit","body":"'"${body}"'"' https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/issues
workflows:
  version: 2
  audit:
    #triggers:
    #  - schedule:
    #      cron: "0 0 * * *"
    #      filters:
    #        branches:
    #          only:
    #            - master
    jobs:
      - audit_job
