version: 2.1

jobs:
  audit_job:
    docker:
        - image: circleci/node
    steps:
      - checkout
      - run:
          name: "npm audit fixコマンドで依存パッケージを更新する"
          command: |
            npm audit fix
      - run:
          name: "Gitのセットアップ"
          command: |
            git config user.name "CircleCI"
            git config user.email "circleci@example.com"
      - run:
          name: "更新結果をコミットする"
          command: |
            branch="npm_audit/${CIRCLE_SHA1}"
            git branch $branch
            git checkout $branch
            git add package.json package-lock.json
            git commit -m "Security Update from ${CIRCLE_BUILD_URL}"
            git push origin $branch
      - run:
          name: "GitHub PRを作成する"
          command: |
            curl -u "${GITHUB_USER}":"${GITHUB_TOKEN}" -X POST -i \
                https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pulls \
                -d @- \<< EOF
                {
                    "title": "npm audit fix",
                    "base": "master",
                    "head" : "${CIRCLE_PROJECT_USERNAME}:${branch}"
                }
            EOF
workflows:
  version: 2
  audit:
    #triggers:
    #  - schedule:
    #      cron: "0 0 * * *"
    #      filters:
    #        branches:
    #          only:
    #            - master
    jobs:
      - audit_job
